### ISSUE TITLE
[Bug]: the music doesnt sound

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaaasdasd** [Mod-Sauce/IamMusicPlayer_FIX#38]
### Already reported ? *

- [x] I have searched the existing open and closed issues.

### Regression?

No

### Mod Version

3.22.0-alpha.7

### Mod Loader

Fabric

### Description

When uploading a song, the mod reads the URL when I upload it on YouTube, I click on test song and it only plays for 1 second and then stops without having played audio. PD: The option to upload files locally by following the upload parameters does not work either.

### How to Reproduce

I upload the song via the YouTube URL, the mod recognizes it and there is no audio playback.

### Logs, Images or Videos and the other Mods you added

this is the link for the log: https://mclo.gs/KkcfQOX

**Comment by Kako-v** [comment]
same problem

**Comment by Shadowbee27** [comment]
@aaaaaaaaaaaaaaasdasd please update otyacraft engine to our version [modrinth](https://modrinth.com/mod/otyacraft-engine-renewed/) [curse forge](https://www.curseforge.com/minecraft/mc-mods/otyacraft-engine-renewed).
@Kako-v I responded to you in your issue

**Comment by aaaaaaaaaaaaaaasdasd** [comment]
@Shadowbee27 I have updated the otyacraft engine to version 3.7.1 and I have exactly the same error.
log link: https://mclo.gs/JuYc7t9

**Comment by Shadowbee27** [comment]
It should be fixed now

**Comment by aaaaaaaaaaaaaaasdasd** [comment]
It's not fixed, the same error persists.

**Comment by Shadowbee27** [comment]
We rolled back some changes it should work now

**Comment by Mooo0042** [comment]
You may have to delete the iammusicplayer folder in your Minecraft directory

**Comment by Mooo0042** [comment]
OP failed to response will be closed, reopen when the error persist
